#!/bin/bash

# 创建一个空文件
# Usage:
#       sh createEmptyFile.sh
#       ./createEmptyFile.sh 19M
#       ./createEmptyFile.sh 1G
#       ./createEmptyFile.sh 19M largefile

# ============Main============
#dd if=/dev/zero of=largefile bs=1M count=19

if [ $# -eq 0 ]; then
    echo "Usage: "
    echo "  $0 <size> [filename]"
    echo "  size: The size of the file to create."
    echo "  filename: The name of the file to create."
    exit 1
fi

size=$1
filename=$2

if [ -z $filename ]; then
    filename="largefile"
fi

dd if=/dev/zero of=$filename bs=1 count=0 seek=$size > /dev/null 2>&1

echo "Created $filename with size $size."


